import "~/styles/globals.css";
import Footer from "~/components/layout/Footer";
import { customFont } from "~/lib/fonts";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${customFont.variable}`}>
      <body className="font-custom">
        {children}
        <Footer />
      </body>
    </html>
  );
}
